language: c
stages:
  - compile files
  - run files
jobs:
  include:
    -stage: compile files
      before_script:
        - cd HW_behaviour
      script:
        - gcc main.c operations.c -o outputRun
    -stage: run files
      before_script:
        -cd HW_behaviour
      script:
        - ./outputRun
