language: c

stages:
  -name: compile files
  -name: run files
  
before_install:
  # set up awscli packages
  - pip install --user awscli
  - mkdir -p ~/$BACKUP_EXEC_FILES
  - aws s3 sync s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER ~/$BACKUP_EXEC_FILES
  
jobs:
  include:
    - stage: compile files
      name: "compile HW files"
      before_script:
        - cd HW_behaviour
      script:
        - gcc main.c operations.c -o ~/$BACKUP_EXEC_FILES/outputRun
    - stage: compile files
      name: "compile tester files"
      before_script:
        - cd tester_behaviour
      script:
        - gcc main.c unity/unity.c test_operations.c ../HW_behaviour/operations.c -o ~/$BACKUP_EXEC_FILES/outputTest
        
    - stage: run files
      name: "run HW files"
      before_script:
        - cd HW_behaviour
      script:
        - .~/$BACKUP_EXEC_FILES/outputRun
