language: c
jobs:
  include:
    -stage: compile
      name: "building files HW_behaviour"
      before_script:
        - cd HW_behaviour
      script:
        - gcc main.c operations.c -o outputRun



    -stage: test
      name: "running HW_behaviour"
      before_script:
        - cd HW_behaviour
      script:
        - ./outputRun

