language: c
jobs:
  include:
    - stage: compile
    - name: "build1"
    - before_script:
      - cd HW_behaviour
    - script:
      - gcc main.c operations.c -o outputRun

    - stage: test
    - before_script:
      - cd HW_behaviour
    - script:
      - ./outputRun

